### ISSUE TITLE
Drivers directory!

### ISSUE THREAD

**Issue by aadrian** [krpors/gimlet#1]
Please create a `/drivers` directory where users can copy their drivers, in order not to mix them with the application JARs from `/lib`

**Comment by krpors** [comment]
Sounds like an OK and easy fix. The real problem though is how I can make the configuration of the drivers as easy as possible (even with a new release). I guess I have to meddle with a configuration option (extra configurable classpath). But for now I can add a `drivers` directory in the assembly I suppose.
