### ISSUE TITLE
Operations on more than one connection?

### ISSUE THREAD

**Issue by aadrian** [krpors/gimlet#2]
Any plans allowing operations on more than one connection?

It seems that quite allot of cases involves work on more than one DB (and sometimes those are not even the same DB type, or support DB Link like Oracle to be able to work with a single connection).

Thank you.

**Comment by krpors** [comment]
Interesting use-case I suppose. It wasn't my initial target solution but I'll have to think about it (in terms of UI and quite possibly the impact of refactoring).

**Comment by krpors** [comment]
Been thinking about it. I guess your original problem is that you want to make drill-down, except the target is not the same database, right? 

In that case, I could make an additional context sub-menu to select a different active connection, and make it execute on that.

**Comment by aadrian** [comment]
> Been thinking about it. I guess your original problem is that you want to make drill-down, except the target is not the same database, right?

Yes. 
Sometimes there are different DBs (even different DB types), other times are just different users that are not allowed to see every schema and table, so more than one connection (with different user) is required to analyze a certain problem.

*In other cases would be nice to be able execute the same steps, the same way (like a replay) on a different connection - e.g. 7 drilldown steps on the Test DB, to be performed on the Production DB too, in order to be able to compare them side by side :) .*

> In that case, I could make an additional context sub-menu to select a different active connection, and make it execute on that.

This would probably solve most use cases. 

If a "short name" for the connection would be also displayed in the drill down tree, e.g. "Get product item - (db=oracle)" instead of the actual in https://camo.githubusercontent.com/00812d5635e93a434361565e02567adbed3f1aa8/68747470733a2f2f692e696d6775722e636f6d2f494934546863592e706e67 , than it would be easy to use even for complex drill downs and it would no confusion.

Thank you!

**Comment by krpors** [comment]
I've been playing around a bit. This is the thing I came up with:

![](https://i.imgur.com/GoEKLgw.png)

In the screenshot, I am currently in the "In memory HSQL database as SA" connection. Depending on how many connections are open, an extra submenu will be displayed per connection (in this case it's "HSQL file as SA"). Using that submenu, you can execute the same subqueries, except on a different connection.

I'm not sure if it covers your use-case. If you want, you can try it out via the [interconn](https://github.com/krpors/gimlet/tree/interconn) branch. Ideas or comments are welcome!

**Comment by aadrian** [comment]
> This is the thing I came up with: ...
> Using that submenu, you can execute the same subqueries, except on a different connection.

@krpors  wow, this looks great!

> .. you can try it out via the interconn branch ...

Building with `mvn clean package assembly:single` as described in the https://github.com/krpors/gimlet#compiling-and-packaging section, seems to fail. Had to run it with `-DskipTests`

> Ideas or comments are welcome!

So far looks very very good :) . 
For he various smaller improvement comments I'll make separate tickets.

**Comment by krpors** [comment]
> Building with mvn clean package assembly:single as described in the https://github.com/krpors/gimlet#compiling-and-packaging section, seems to fail

What error did you get? I'm not getting any errors on my end.

**Comment by krpors** [comment]
OK, thanks! I guess that's because of Windows. TBH I haven't tested the build on Windows before (only the execution of the application). My work laptop has Windows (all my others computers don't :)) so I can check it out, probably tomorrow.

**Comment by krpors** [comment]
As I suspected it was a Windows thing (EOL issue and CRLF stuff). I pushed to `master` and to `interconn` branched and it seems to compile ok.
