### ISSUE TITLE
Copy as Plain Text.

### ISSUE THREAD

**Issue by aadrian** [krpors/gimlet#4]
The functionality from the context menu on a Table "Copy as Plain Text", looks more like "Copy as a Wiki Table" .

It is very useful, but not what most users would expect.

Maybe Plain text should be just plain text (tab separated, so that it can be pasted into any spreadsheet) ?

Also I'm not sure if the encoding of the copied text is the usual default to UTF-8, since most tools seems to recognized it as UTF-16 on Windows (but maybe this is a tool problem).

**Comment by krpors** [comment]
Yeah I could build in an "Advanced copy" or the like, mimicking a bit what SquirrelSQL has (CSV files, choosing separator etc.). I'll check it out.

**Comment by krpors** [comment]
I added a dialog where the text copying can be changed depending on some options:

![Advanced copy](http://i.imgur.com/0y3kAad.png)

Any separator character sequence can be chosen, including a `\t` for a tab character. I also added a preview section so you can preview a subset (max 10) of the actual selected rows.

**Comment by krpors** [comment]
Closed. Made release 1.3 to include this one.

**Comment by aadrian** [comment]
@krpors thank you for the new release! Very helpful tool 😃   !
